### ISSUE TITLE
Which serial port?

### ISSUE THREAD

**Issue by wx4cb** [stronnag/LTM-lua#5]
which serial port do we use on the tx16s? left or right on the bottom?

also, i assume it works fine turning the CRSF into LTM using the crossfire module as there's a CRSF lua script in there?

**Comment by stronnag** [comment]
I'm not familiar with the tx17s. 

On radios such as the RadioMaster TX16S where there are two serial ports, it's the port you configure as "LUA" on the radio (SYS/Hardware); your choice. I use the four pin port on the left (serial 1).

It should work with CRSF, modulo OpenTX / CRSF bugs (like the flight mode is not set with OpenTX 2.3.10;  the bug is fixed in the 2.3.11 pre-release nightlies (which seem stable to me). Note also that for the TX16S at least,  an OpenTX bug in 2.3.9 meant that the serial ports were not powered and thus useless. So for CRSF, in practice you need a nightly or wait for 2.3.11 to have both working ports and useful telemetry.

**Comment by wx4cb** [comment]
@stronnag hope you had a good christmas jonathan

yea  i meant the TX16S was just a typo.

So... update to 2.3.10 nightly, Set the serial port to LUA and use the left port.. .got it :D

**Comment by stronnag** [comment]
@wx4cb, I guessed as much (the typo). A 2.3.11 nightly. 
The port pinout is in the manual (on the RM web site).

**Comment by wx4cb** [comment]
> @wx4cb, I guessed as much (the typo). A 2.3.11 nightly.
> The port pinout is in the manual (on the RM web site).

ty. working on the nightly now

**Comment by stronnag** [comment]
FYI, 2.3.11 is now released.
